### PR TITLE
Icon Changes

### PR DESCRIPTION
**Pull request by Jithin-Jude**
App Icon changed from ic_launcher.png to gis_logo.png
Splash Screen logo changed from ic_launcher.png to gis_logo.png

### CODE REVIEW

**Comment by Rahulxx01** [comment]
Plz resolve the conflicts @Jithin-Jude

**Comment by Jithin-Jude** [comment]
@Rahulxx01 , conflicts resolved.

**Comment by amarjeetkapoor1** [comment]
Name of icons should have ic_ prefix.

**Comment by amarjeetkapoor1** [comment]
Plus remove .idea files from your commit.

**Pull request closed without merging**
