### PR TITLE
Adds Fragments 

### PR DESCRIPTION
**Pull request by jhaanuj2108**
Fragments created for each components of the Navigation Drawer.

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
Remove modules.xml and vcs.xml.Plus wait till project structure gets added

**Comment by amarjeetkapoor1** [comment]
And if possible rename the branch or try to give relevant name next time.

**Comment by jhaanuj2108** [comment]
@amarjeetkapoor1 Sorry and thanks for your feedback. I'll keep that in mind from next time onwards. 😃

**Comment by Rahulxx01** [comment]
@jhaanuj2108 while creating a Fragment give it some names so that all can understand 
If your creating Fragment for Projects Activity then just name it *ProjectsActivityFragment* or just *ProjectsFragment*

**Comment by jhaanuj2108** [comment]
Yes, I do agree that we would need a home page first but what you are saying that

>  When we load all the fragments then we navigate back all the fragments are displayed again which we don't want.

 ---> this is not happening in my case. And yes I should have named it properly, my fault. Next time onwards I will keep that in mind.

**Comment by TheRaider** [comment]
Why all the fragments are named as activities?? Please rename them because later when the project starts the contributors will be in confusion seeing the name of it. Just replace activity with fragment in the name of every fragment created and do a commit.

**Comment by jhaanuj2108** [comment]
@TheRaider Okay. I will change that and again place a new pull request after some time.

**Comment by amarjeetkapoor1** [comment]
One last thing as main motive of this PR is navigation between Fragments . So, keep changes related to 
layout xml files minimum.

**Comment by jhaanuj2108** [comment]
@amarjeetkapoor1 I have just added a new layout for each component of navigation drawer which was not present there to attach it to the fragment and a simple text view inside each layout activity file is added. That's all that is done.

**Comment by amarjeetkapoor1** [comment]
I meant keep attributes of those TextView to a minimum. Plus related to my previous comment on deleting module.xml. I would like to get view of someone expert.

**Pull request merged**
