### PR TITLE
Feature login screen UI

### PR DESCRIPTION
**Pull request by derrickabreo**
## Description
Modified login Screen UI (Only the xml and affected files)

## Changes/Updates 
1. Modified content_login.xml file
2.  Added commonly used dimensions in dimens.xml 
3. Added Roboto font
4. Added String values in string.xml
5. Added extra color in color.xml

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
Remove .idea files and commit again and for mods and co-mods merge with squash and merge option only.

**Comment by derrickabreo** [comment]
@amarjeetkapoor1 I Have removed .idea files before pushing the changes to github.

**Comment by amarjeetkapoor1** [comment]
Sorry, For that. I have requested the respective mod for review. 

P.S. Can you add sign in functioning with firebase as we already have a sign-in page but its not functioning, plus no sign-up page

**Comment by derrickabreo** [comment]
@amarjeetkapoor1 Sure! But more information would be helpful.

**Comment by derrickabreo** [comment]
@knightcube SignUp screen with just email and password registration right?

**Comment by knightcube** [comment]
yup @derrickabreo

**Comment by amarjeetkapoor1** [comment]
@Rahulxx01 @knightcube  Should we merge it to be specific squash and merge?

**Comment by knightcube** [comment]
Yes we can go ahead and merge it

**Pull request merged**
