### PR TITLE
Enhanced login UI

### PR DESCRIPTION
**Pull request by xsahil03x**
## Description
Modified login UI **(Xml + Resources)**

## Changes/Updates
1. Modified **content_login.xml** file.
2. Added and modified **selectors**.
3. Added **CardView (support library)**
4. Added String values in **string.xml**.
5. Added **gray** color in **color.xml**.
6. Changed **(gis_logo + bg_login)**.

### CODE REVIEW

**Comment by Rahulxx01** [comment]
@xsahil03x Plz resolve the conflicts and PR again.

**Comment by Rahulxx01** [comment]
Plz resolve the occurring conflict in your colors.xml file and PR again @xsahil03x

**Comment by xsahil03x** [comment]
@Rahulxx01 I solved the conflict, you can merge now. 😄

**Comment by xsahil03x** [comment]
@Rahulxx01 Resolved, please merge now 😄

**Comment by xsahil03x** [comment]
@knightcube please always give a proper reason or feedback before closing any PR. 😊

**Pull request closed without merging**
