### PR TITLE
Stories Fragment Code is added along with UI

### PR DESCRIPTION
**Pull request by TheRaider**

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
@TheRaider It seems perfect Should I merge or there are more changes coming?

**Comment by amarjeetkapoor1** [comment]
Just found a little problem that on clicking back button when on stories an empty screen appears but It can be dealt with in future.

**Comment by amarjeetkapoor1** [comment]
@Rahulxx01 Just a general advice never temper with others person branch unless they know about it.

**Comment by Rahulxx01** [comment]
@amarjeetkapoor1 Agreed I got to know that the conflict was in just one file and it was just a single color code line so I decided to do it myself. In Future will take care of it.

**Comment by TheRaider** [comment]
@amarjeetkapoor1 Yes , merge it. I have exams going on now. So I cannot make 
any changes for a few days. I think we can remove the bug have specified later also because we will do it  when we do for all other fragments. If there are no conflicts , kindly merge it

**Pull request merged**
