### PR TITLE
(Issue #18) Added Splash Screen with animations

### PR DESCRIPTION
**Pull request by tavishjain**
(Issue #18) Added the splash screen along with the animations. Suggestions welcomed !!

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
Could you correct the code as your code is going beyond the 100 char limit per line? 
Rest I have asked for review by other moderators. We will merge after review from them.

**Comment by Saurav2304** [comment]
Kindly refer https://github.com/ribot/android-guidelines/blob/master/project_and_code_guidelines.md section 2.2.15

**Comment by tavishjain** [comment]
Since this is the first time I am working on any project (and hence github) , I didn't knew that such rules existed !! 
So I will take care from the next time ✌️✌️

**Comment by amarjeetkapoor1** [comment]
Taking care next time is okay. But you can still correct mistake in this PR also. Just make the changes and commit we will automatically get changes.

**Comment by tavishjain** [comment]
@amarjeetkapoor1 I sat down again on my pc to make the required changes , but then I realised that none of the lines exceeds 100 characters limit. Can you point any line which you felt to be having more than 100 charecters ?

**Comment by Rahulxx01** [comment]
Once corrected we will review it.

**Comment by sidhuparas** [comment]
@tavishjain Lines 55-57 and 67-69 (Including Indentation Spaces) in `SplashScreenActivity.java`.

**Comment by tavishjain** [comment]
Changed the code according to the standard code limit. Please review.

**Comment by tavishjain** [comment]
@amarjeetkapoor1 @Rahulxx01 @Saurav2304 @sidhuparas 
Changed the code according to the standard code limit

**Comment by Rahulxx01** [comment]
@tavishjain nice work

**Comment by tavishjain** [comment]
Thank you @Rahulxx01 :-)

**Pull request merged**
